### ISSUE TITLE
**Definir interfaz modelo**

### ISSUE THREAD

**Issue by miguescri** [UNIZAR-30226-2018-05/Modelo#1]
Especificar los métodos y objetos que serán ofrecidos a la capa de vista.

Ejemplos:
- Un método que toma un entero identificador de una lista de reproducción y devuelve una lista de objetos *Cancion* con información de cada canción y su carátula (esto no tiene por qué corresponderse con una única llamada a la API del servidor, pues, por ejemplo, podría no interesar en general que la API devolviera listas de imágenes en una sóla consulta [bandwith vs latency]).

**Comment by miguescri** [comment]
Por favor, cuando esté lista la interfaz, haced el pull request para que la revisemos.

**Comment by robertoccu** [comment]
Con el cambio en la estructura de la capa de Modelo este repositorio pasará a estar inactivo, archivado y únicamente para lectura.
